stages:
  - buildProd
cache:
  key:  "%CI_BUILD_REF_NAME%"
  paths:
   - node_modules/
prod:
  stage: buildProd
  only:
    - release
  script:
    - cnpm i;
    - npm run build:prod;
    - rm -rf /home/www/webgl/*;
    - cp -r dist/* /home/www/webgl;
  tags:
    - 118-linux
